apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp
  labels:
    app: voteapplb
spec:
  selector:
    matchLabels:
      app: voteapplb
  replicas: 2
  template:
    metadata:
      labels:
        app: voteapplb
    spec:
      containers:
      - name: voteapp
        image: whujin11e/public:azure_voting_app
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 250m
        env:
        - name: REDIS
          value: "clustredis"
        - name: STRESS_SECS
          value: "2"
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redispw
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: clusterapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: voteapplb